### ISSUE TITLE
Error with every Sim loaded

### ISSUE THREAD

**Issue by huughoog** [thepancake1/TS4-SimRipper#6]
I am using the latest version.

I receive these errors each time I attempt to load a Sim:

Can't find SimModifier 0xC5F6763E-0x00000000-0xE7C1C1D624F1D9DE
Can't find SimModifier 0xC5F6763E-0x00000000-0xD22094DF21E9C703
Can't find SimModifier 0xC5F6763E-0x00000000-0xEA021C57920F7BF9
Can't find SimModifier 0xC5F6763E-0x00000000-0xD8FA0ED7B2BA1C25
Can't find SimModifier 0xC5F6763E-0x00000000-0xE886D2C4AED80B21
Can't find SimModifier 0xC5F6763E-0x00000000-0xDABC87F05D4F0B02
Can't find SimModifier 0xC5F6763E-0x00000000-0xAC61A033BF0DE4F9

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at TS4SimRipper.Form1.UpdateSlotTargets() in C:\Users\theoj\Documents\TS4-SimRipper\PreviewControl.cs:line 1193
   at TS4SimRipper.Form1.GetCurrentModel(Boolean skinOnly, Int32 desiredLevelOfDetail) in C:\Users\theoj\Documents\TS4-SimRipper\PreviewControl.cs:line 646
   at TS4SimRipper.Form1.DisplaySim(SimData sim, SimOccult occultState, Int32 desiredLevelOfDetail) in C:\Users\theoj\Documents\TS4-SimRipper\Form1.cs:line 935
   at TS4SimRipper.Form1.sims_listBox_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\theoj\Documents\TS4-SimRipper\Form1.cs:line 376
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Not sure what the problem is, it's been happening only on the newest version. Thank you!

EDIT: I've been removing mods, and it triggers the same result no matter which Sim. The Sim Error troubleshoot logs don't create, instead triggering this error.
[https://cdn.discordapp.com/attachments/592242624795246592/944094401448280074/unknown.png](url)
This has only been an issue this update, as all of my mods have worked without problem with previous iterations of the program.

**Comment by thepancake1** [comment]
@huughoog Do you have any custom sliders installed? I checked these sliders and they're not Maxis sliders.

**Comment by huughoog** [comment]
The new update you released fixed the issue. Blessings!
